version: '2'

services:

  data-collector:
    build: ./data-collector
    volumes:
      - ./data/sdc:/landing-zone
    ports:
      - 18630:18630
    stdin_open: true
    tty: true
    container_name: sdc_demo
    depends_on: ["db"]

  db:
    image: mysql:5.6
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3306:3306
    stdin_open: true
    tty: true
    container_name: mysql_sdc_demo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: natty_is_gr8
